### ISSUE TITLE
No audio from Jamma adaptor

### ISSUE THREAD

**Issue by jurkevicz** [forkymcforkface/RGBPi-Bookworm#10]
I just installed this to test on my raspberry pi 5 and Jamma IO board.    Unfortunately no audio. 
There is also a little delay going around the menu that did not exist on raspberry pi 4 rgbpi os.

**Comment by forkymcforkface** [comment]
yes, if you read the description it states that audio only works through a USB dac. The Raspberry Pi devs have not released a gpio audio driver yet. The slow UI is some incompatibility with OS4 UI and the pi5 hardware. If you put the sd card into a pi4 the ui is smooth.
