### ISSUE TITLE
Wrong colors on PAL CRT using PI2SCART

### ISSUE THREAD

**Issue by r0xx0rd-teh-x0xx0r** [forkymcforkface/RGBPi-Bookworm#11]
Hi, i have a PI2SCART header and want to use this together with a Raspi 5 and a PAL CRT.
It installs and boots up fine on my pi5 but the colors are switched.

The original RGBPI-OS 4 on a Pi 4 kind of supports this header by changing the dtoverlay:

`dtoverlay=vc4-vga666-argon,mode6`

to 

`dtoverlay=vc4-vga666-argon`

Essentially removing mode6 from the command line.
Otherwise the color channels are wrong and the image looks like a negative.

I tried the same with the RGUI config.txt by removing mode6 from the line:

`dtoverlay=vc4-kms-dpi-custom,mode6`

However on my pi 5 this doesnt work and the colors are still wrong.
I recognise this is may be a hardware compatibility issue rather than an issue with your RGUI-Pi project, but do you have an idea on how i could correct the colors anyway?

i cant seem to find documentation on the vc4-kms-dpi-custom overlay.

Thanks in advance!

**Comment by riggles1** [comment]
I'm hesitant to answer since it's another adapter, but I posted below what should work, since you should be getting their upcoming DAC instead.
BEWARE, the Pi5 has noisy GPIO for 15kHz RGB, I've tried two different Pi5, multiple CRT's, multiple PSU's, multiple hats (RGBPi+Pi2Scart I had laying around), the image has this very slight rolling erratic S-shaped noise across the screen, visible in full white screens or big areas with the same color. Just swapping back to the Pi4 and the noise is gone completely, using any combination of adapter etc. I'm sensitive to video noise though, and have sharp CRT's, so your tolerance might be different.

In any case, Pi5 GPIO also lacks interlacing, and is still limited to 18-bit color with these hats, it's only suitable for systems up until the PS1, you'll start seeing color banding for Dreamcast or Gamecube, and again, no 480i support which these systems use for TVs.

I highly highly advice to stick with Pi4 for now and wait for the proper RGBPi HDMI DAC that's in the works, with their DAC you'll also get proper 24-bit color depth, making the more advanced systems that Pi5 can handle presented the way they should, no color banding and with working interlacing.

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d,noaudio=on
dtoverlay=vc4-vga666
dtoverlay=audremap,pins_18_19
max_framebuffers=1

**Comment by forkymcforkface** [comment]
> Hi, i have a PI2SCART header and want to use this together with a Raspi 5 and a PAL CRT.
> It installs and boots up fine on my pi5 but the colors are switched.
> 
> The original RGBPI-OS 4 on a Pi 4 kind of supports this header by changing the dtoverlay:
> 
> `dtoverlay=vc4-vga666-argon,mode6`
> 
> to 
> 
> `dtoverlay=vc4-vga666-argon`
> 
> Essentially removing mode6 from the command line.
> Otherwise the color channels are wrong and the image looks like a negative.
> 
> I tried the same with the RGUI config.txt by removing mode6 from the line:
> 
> `dtoverlay=vc4-kms-dpi-custom,mode6`
> 
> However on my pi 5 this doesnt work and the colors are still wrong.
> I recognise this is may be a hardware compatibility issue rather than an issue with your RGUI-Pi project, but do you have an idea on how i could correct the colors anyway?
> 
> i cant seem to find documentation on the vc4-kms-dpi-custom overlay.
> 
> Thanks in advance!

Hello, yes I have actually been working on a new version and will release it this week. I've been working on getting the dpi24 hat working, and the vga666 fix will come along with it. These are just drivers and overlays that had to be configured properly. Cheers!

**Comment by forkymcforkface** [comment]
> I'm hesitant to answer since it's another adapter, but I posted below what should work, since you should be getting their upcoming DAC instead. My advice is to buy that when it's out. 
> Reasons:
> The Pi5 has noisy GPIO for 15kHz RGB, I've tried two different Pi5, multiple CRT's, multiple PSU's, multiple hats (RGBPi+Pi2Scart I had laying around), the image has this very slight rolling erratic S-shaped noise across the screen, visible in full white screens or big areas with the same color. Just swapping back to the Pi4 and the interference is gone completely, using any combination of adapter etc, Pi4 always looks perfectly clean. I'm sensitive to video noise though, and have sharp CRT's, so your tolerance might be different.
> 
> In any case, Pi5 GPIO also lacks interlacing, and is still limited to 18-bit color with these hats, it's only suitable for systems up until the PS1, you'll start seeing color banding for Dreamcast or Gamecube, and again, no 480i support which these systems use for TVs.
> 
> I highly highly advice to stick with Pi4 for now and wait for the proper RGBPi HDMI DAC that's in the works, with their DAC you'll also get proper 24-bit color depth, making the more advanced systems that Pi5 can handle presented the way they should, no color banding and with working interlacing.
> 
> 
> dtoverlay=vc4-kms-v3d,noaudio=on
> dtoverlay=vc4-vga666
> dtoverlay=audremap,pins_18_19
> max_framebuffers=1

I recently modified the driver completely. Maybe it works now? I'll be pushing the new version this week.

**Comment by r0xx0rd-teh-x0xx0r** [comment]
Sorry i didn't reply, i will try it out!

**Comment by r0xx0rd-teh-x0xx0r** [comment]
The colors are still shifted unfortunately and the config from @riggles1 resulted in a black screen unfortunately.

I will stick with my Pi4 for now and wait untul the hdmi dac comes out. 

@riggles1 do you roughly know when it will be released?
and will it support only raspi's or also other devices?

**Comment by riggles1** [comment]
> The colors are still shifted unfortunately and the config from @riggles1 resulted in a black screen unfortunately.
> 
> I will stick with my Pi4 for now and wait untul the hdmi dac comes out.
> 
> @riggles1 do you roughly know when it will be released? and will it support only raspi's or also other devices?
Honestly, probably a bit over a year if I were to guess, getting the drivers made for a HDMI DAC like that.

As for the config, you're probably not implementing it correctly, I've personally ran the following full configs when testing:
Pi4: https://pastebin.com/cFTAu9QK
Pi5: https://pastebin.com/fkudXFff

(you can remove the lines disabling bluetooth if you still want that, that's just added for quicker booting)

**Comment by forkymcforkface** [comment]
> > The colors are still shifted unfortunately and the config from @riggles1 resulted in a black screen unfortunately.
> > I will stick with my Pi4 for now and wait untul the hdmi dac comes out.
> > @riggles1 do you roughly know when it will be released? and will it support only raspi's or also other devices?
> > Honestly, probably a bit over a year if I were to guess, getting the drivers made for a HDMI DAC like that.
> 
> As for the config, you're probably not implementing it correctly, I've personally ran the following full configs when testing: Pi4: https://pastebin.com/cFTAu9QK Pi5: https://pastebin.com/fkudXFff
> 
> (you can remove the lines disabling bluetooth if you still want that, that's just added for quicker booting)

Those probably wont work since I redid the entire driver. the driver and the overlay work with each other. not sure what the vga666 overlay is pointing at.

**Comment by forkymcforkface** [comment]
> The colors are still shifted unfortunately and the config from @riggles1 resulted in a black screen unfortunately.
> 
> I will stick with my Pi4 for now and wait untul the hdmi dac comes out.
> 
> @riggles1 do you roughly know when it will be released? and will it support only raspi's or also other devices?

Did you follow the github instructions and change the video output to VGA666? Everything is done in the OS4 UI, and there is no need to modify the config.txt. The colors are going to be off in the beginning since the initial driver is for the rgb-pi cable.

**Comment by forkymcforkface** [comment]
@r0xx0rd-teh-x0xx0r please let me know if you applied the vga666 driver that is in the directions. I do not have a pi2scart to test. It should be working fine though.

**Comment by r0xx0rd-teh-x0xx0r** [comment]
Sure, you mean your pastbin configs? I can test them in a few hours when im back from work, i have overread them and did not test them yesterday (Im in the CET timezone btw.)

**Comment by r0xx0rd-teh-x0xx0r** [comment]
> Sure, you mean your pastbin configs? I can test them in a few hours when im back from work, i have overread them and did not test them yesterday (Im in the CET timezone btw.)

Also would a dmesg log help you? I can still access the pi with ssh even when i had a blackscreen.

**Comment by forkymcforkface** [comment]
No do not use those at all those were not from me, you need to replace the config.txt with the original unmodified version I just uploaded here.
[config.txt](https://github.com/user-attachments/files/17416745/config.txt)

 then follow the instructions that are in the repo.  Try VGA666 setting

After migrating OS4, scan for games before mounting a drive. Open ports and there are options available:
Lo-tech VGA888 (24bit color)
Retrotink Ultimate (use VGA888)
RGB-Pi cable (full 18bit color)
VGA666 (does not display full 18bit colors)
120hz VGA Option. Must apply this with a normal CRT first.
You must run the pi zero2 Pi3 script if you are running on those systems.
USB Audio Dac required even for Pi Zero2, Pi3, Pi4. Can probably be fixed, but pi5 is the focus.

**Comment by forkymcforkface** [comment]
@r0xx0rd-teh-x0xx0r did running the vga666 script from the os4 ui work for you?

**Comment by forkymcforkface** [comment]
closing since I dont have a pi2scart to test and user did not respond.
