### ISSUE TITLE
Vga888

### ISSUE THREAD

**Issue by pazuzu72** [forkymcforkface/RGBPi-Bookworm#12]
Raspberry Pi 3+ with LoTech works with RetroTink ultimate no! Yet they should use the same system (VGA888) right? I can't find the option to enable retrotink.

**Comment by forkymcforkface** [comment]
Did you set it to vga888 per the instructions? If so can you send a picture of the screen so I can see the colors?

**Comment by pazuzu72** [comment]
Of course it is set to VGA888! If I use the Lo-tech it is perfectly visible. If I use the RetroTink sometimes when loading I see the RGB-PI logo for a moment and then the screen remains black.

The RetroTink ultimate works perfectly with other distros.

**Comment by forkymcforkface** [comment]
Ok, Ill have to see how the pinout is on the retrotink. OS4 uses a custom driver that can change the resolution on the fly, while those other distros use the generic dpi24 driver. I assumed since they both use all the pins that it would work correctly.

**Comment by pazuzu72** [comment]
In fact I don't understand what the problem could be. On all distros the settings for Lo-tech and RetroTink ultimate are the same. I can't even understand if it's just a display problem because there is no music in the converted RGB-PI version.

But judging by the status LED flashes it doesn't seem to boot as it should. But I could be wrong.

**Comment by forkymcforkface** [comment]
closing as I dont have a retrotink ultra to test on.
