### ISSUE TITLE
Composite output?

### ISSUE THREAD

**Issue by JanitorHead** [forkymcforkface/RGBPi-Bookworm#13]
Hi, first of all, awesome work man!

I have a question, would it be possible to use the composite output of the raspberry pi 5 with the system? I see on the video https://www.youtube.com/watch?v=CJom1TIRI6g that at the beginning the output appears to be composite, I just love composite.

**Comment by forkymcforkface** [comment]
I use a scart to S-video/composite converter that is why you are seeing the dot crawl. Os4 is hard coded to gpio output only. Also composite doesn't support all the resolutions the games require anyway
