### ISSUE TITLE
Bluetooth does not work

### ISSUE THREAD

**Issue by Macs75** [forkymcforkface/RGBPi-Bookworm#7]
I'm trying to associate the BT controller 8Bitdo, it does not find it with the search button, and neither the 2.4 dongle works, but with a wired cable it is immediately recognised.

On the Pi4 it was working.

Happy to help with any test if needed

**Comment by Macs75** [comment]
working on it a bit more I managed to get the controller appear in the list of BT for pairing, the I click on pairing and the controller confirms ok, but when I esc from the menu the controller does not appear in the list of devices and when I go in the BT menu it is disappeared, but the controller does not blink and it seems still paired. So it seems something is not stored, but the BT layer per se may work. 
I wonder if the fact I connected before in wired mode could have messed it, but the profiles were different and it appeared with different names.

**Comment by forkymcforkface** [comment]
Bt driver will be added soon

**Comment by forkymcforkface** [comment]
Bt driver added
