### ISSUE TITLE
USB wired controller not working.

### ISSUE THREAD

**Issue by Welltall** [forkymcforkface/RGBPi-Bookworm#9]
I've been using a sn30 wired 8bitdo controller on the pi4. After finishing the downloads for pi 5 os 4, my controller is not working at all. The controllers light turns on but does not work with the software.

**Comment by forkymcforkface** [comment]
Does it work on regular os4 on the pi4?

**Comment by forkymcforkface** [comment]
I'll look into it.

**Comment by Welltall** [comment]
> I'll look into it.

Thanks. I ordered an official power supply. I was using my mac usb c charger.

**Comment by Welltall** [comment]
Thanks. I ordered an official power supply. I was using my mac usb c charger.

**Comment by Welltall** [comment]
Thanks. I ordered an official power supply. I was using my mac usb c charger.

**Comment by Welltall** [comment]
Thanks. I ordered an official power supply. I was using my mac usb c charger.

**Comment by Welltall** [comment]
So new power supply didn't do anything. I used a xbox one controller wired and it worked. Looks like it still doesn't recognize my 8bitdo sn30 pro wired controller even tho the controller light turns on. The pi4 works with it on os4. Thanks

**Comment by forkymcforkface** [comment]
looks to be an issue with the xone driver. next update will have this fix.

**Comment by Welltall** [comment]
Thanks! Did the next update come out yet?

**Comment by forkymcforkface** [comment]
Root pw is rgbpiunlocked. You can update xone through ssh. No more updates since replayOS will be coming out in May it sounds like.
